[package]
name = 'codelist'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.65'

[lib]
crate-type = [ 'staticlib' ]
name = 'codelist'

[dependencies]
extendr-api = '*'
codelist-rs = { git = 'https://github.com/albersonmiranda/codelist-tools.git', package = 'codelist-rs' }